### ISSUE TITLE
Unable to install adobe dc, openvpn and vlc

### ISSUE THREAD

**Issue by erppaul** [Installomator/Installomator#1033]
Hello, 
I am not able to install these 3 applications. I have attached the log. Unfortunately, the debug mode did not give me more either.
Do you have a solution for me?
[openvpn error.txt](https://github.com/Installomator/Installomator/files/11419435/openvpn.error.txt)
[vlc error.txt](https://github.com/Installomator/Installomator/files/11419436/vlc.error.txt)
[adobe error.txt](https://github.com/Installomator/Installomator/files/11419437/adobe.error.txt)

**Comment by scriptingosx** [comment]
Since I cannot reproduce these issues and all of these apps fail mounting the disk image, my guess would be that you have a security tool installs that interferes or prevents the mounting of disk images. Another (less likely) possibility would be that some network tool/security is inspecting and modifying the download, so the data downloaded is not actually a dmg, but an error message from the proxy/security tool.

**Comment by erppaul** [comment]
The device is completely naked and has no security software or network restrictions. It must be something different.

**Comment by scriptingosx** [comment]
That may well be the case. But since I cannot recreate the issue, it has to be something different which is specific to your setup?

When you run Installomator with `DEBUG=1` the download will be stored in the same folder as the script and not deleted when the run is complete. you can inspect the download with a text editor to see if it really is a dmg or some html error message

**Comment by erppaul** [comment]
<img width="736" alt="screen" src="https://user-images.githubusercontent.com/132888724/236843510-379cd493-4ec6-41aa-8662-0af7236364c0.png">
It seems that it is not a html error file. I also can not start/ mount the dmg manually.

**Comment by erppaul** [comment]
[debugvlc.txt](https://github.com/Installomator/Installomator/files/11422485/debugvlc.txt)

**Comment by scriptingosx** [comment]
The checksums of your download are off. I get different checksums and it mounts for me: 

```
2023-05-09 09:09:23 : DEBUG : vlc : Debugging enabled, dmgmount output was:
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $D0BFBAC5
Checksumming GPT Header (Primary GPT Header : 1)…
GPT Header (Primary GPT Header : 1): verified   CRC32 $DBE6682E
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $CD5EA02F
Checksumming  (Apple_Free : 3)…
(Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
disk image (Apple_HFS : 4): verified   CRC32 $8DAA91D1
Checksumming  (Apple_Free : 5)…
(Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $CD5EA02F
Checksumming GPT Header (Backup GPT Header : 7)…
GPT Header (Backup GPT Header : 7): verified   CRC32 $CAD7D494
verified   CRC32 $1DF6E624
/dev/disk4          	GUID_partition_scheme
/dev/disk4s1        	Apple_HFS                      	/Volumes/VLC media player
```

Something is corrupting your download.

**Comment by erppaul** [comment]
I have wiped the system again and reinstalled Ventura. Same problem, unfortunately. Neither the network or any security software can restrict the download.

**Comment by scriptingosx** [comment]
I really can only repeat: _I cannot recreate your issue._ We have several hundreds (if not thousands) of people using Installomator and we would get issues if any one of these labels were generally broken.

I understand that you seem to have excluded my first suspicions. I still believe the error has to be on your side somehow, other wise we would have heard about it.
