### ISSUE TITLE
Display Link Manager is not working 

### ISSUE THREAD

**Issue by Mollahasifahmed** [Installomator/Installomator#1314]
It is saying exit code 2 it means download problem. Others are working, can you please fix it?

**Comment by scriptingosx** [comment]
download for `displaylinkmanager` is working fine for me

**Comment by Mollahasifahmed** [comment]
I tried on M1 Mac, you are on Apple silicon or Intel mac?

**Comment by scriptingosx** [comment]
Apple Silicon

Issues are really not the right place for troubleshooting, we generally recommend joining [the MacAdmins Slack](https://macadmins.org) and asking in the `#installomator` channel.

**Comment by sjurlohne** [comment]
Seing som issues with this too. It downloads 1.9 instead of 1.10.
The appNewVersion variable is grabbing the wrong line.
appNewVersion=$(curl -sfL https://www.synaptics.com/products/displaylink-graphics/downloads/macos | grep "Release:" | sed -n '2p' | cut -d ' ' -f2)
If I run curl -sfL https://www.synaptics.com/products/displaylink-graphics/downloads/macos | grep "Release:"
I get the full list, and as you can see, sed -n '2p' grabs the second line. It should be sed -n '1p'

<p>Release: 1.10 | <time datetime="2023-10-26T12:00:00Z">Oct 26, 2023</time>
<p>Release: 1.9 | <time datetime="2023-07-16T12:00:00Z">Jul 16, 2023</time>
<p>Release: 1.8.1 | <time datetime="2023-03-16T12:00:00Z">Mar 16, 2023</time>
<p>Release: 1.5 | <time datetime="2021-09-08T12:00:00Z">Sep 8, 2021</time>
<p>Release: 5.2.6 | <time datetime="2021-05-21T12:00:00Z">May 21, 2021</time>
<p>Release: 5.2 | <time datetime="2019-07-08T12:00:00Z">Jul 8, 2019</time>
<p>Release: 5.1.1 | <time datetime="2019-04-18T12:00:00Z">Apr 18, 2019</time>
<p>Release: 4.3.1 | <time datetime="2018-10-10T12:00:00Z">Oct 10, 2018</time>
<p>Release: 3.1.1 | <time datetime="2018-10-09T12:00:00Z">Oct 9, 2018</time>
<p>Release: 4.1 | <time datetime="2017-12-21T12:00:00Z">Dec 21, 2017</time>
<p>Release: 2.6 | <time datetime="2016-09-19T12:00:00Z">Sep 19, 2016</time>
<p>Release: 2.5.1 | <time datetime="2016-04-19T12:00:00Z">Apr 19, 2016</time>
<p>Release: 2.2 | <time datetime="2014-06-10T12:00:00Z">Jun 10, 2014</time>

**Comment by sjurlohne** [comment]
Created PR #1337

**Comment by acodega** [comment]
Closing this Issue as the original post is not related to PR.
