### ISSUE TITLE
Microsoft Excel version

### ISSUE THREAD

**Issue by damacguy** [Installomator/Installomator#145]
So, this is really more of an issue for whomever updates the info at macadamins.software... but the version of Excel listed there in the XML is 16.47, but it's actually 16.47.1.

If you look at the "Office for Mac Release History" section it lists 16.47.1, and offers an Excel update there.

I don't know the best way to resolve this. Maybe a regex expression that looks to see if the installed version is newer than the 'current' version being pulled from the 'authoritative' source? That could be helpful for other software titles to possibly.

**Comment by isaacatmann** [comment]
This ultimately is an issue from Microsoft, they post a static URL which always has the "latest" version available at https://go.microsoft.com/fwlink/?linkid=525135 - this link doesn't redirect to the newest version, likely because it's a hot fix?

Given the way the "appNewVersion" functions in the updates @Theile is adding in v.5 this should resolve this if we update the newAppVersion formula to base it off the version we actually download not the version we find on the site.

Additionally scoping should be based on a patch source that provides additional validation (if possible).  Jamf's Patch Reporting will allow you to target only computers that need an update.

@Theile on thing the differs here in our versions is that I've based appNewVersion on the actual package we're getting from Microsoft using the following statement changes:

downloadURL="https://go.microsoft.com/fwlink/?linkid=525135"
appNewVersion=$(curl -is "$downloadURL" | grep ocation: | grep -o "Microsoft_.*pkg" | cut -d "_" -f 3 | cut -d "." -f1-2)

This would effectively negate this issue, but I'm not clear if it would cause more issues for people who are just doing a recurring "update" on all machines without any scoping to machines that need it based on patch reporting...

**Comment by Theile** [comment]
Ny first thought is that our Microsoft Office labels include update information:

updateTool="/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate"
updateToolArguments=( --install --apps XCEL2019 )

So for updates to Excel, this should be used instead.

The primary problem I see is if macadmin.software is not returning the latest version, then we should try to get it in another way. I would say we need the correct latest version for appNewVersion, more than we need it to match what we download. I will look into the above appNewVersion if that is better.  

I will have to look into this updateTool thing, and see how this get used for changed versions.

**Comment by damacguy** [comment]
I like @isaacatmann's method of getting the version from the download site, but I'm going to use the full version and compare it to the installed app's CFBundleVersion (ex. 16.47.21031401). But I also think this may be limited to just one-off single up hot fixes. That hasn't happened in over two years until now (based on the "Office for Mac Release History" of the site.

**Comment by Theile** [comment]
I have also seen Yammer not being versioned correctly on macadmins.software. I will have to take a look to see if there is a better place to get the version.

We can also add this:
bundleID="com.microsoft.package.Microsoft_Excel.app"

Because that has version 16.47.21031401, that currently matches the full version of the download, so:
appNewVersion=$(curl -fsIL "$downloadURL" | grep -i location:  | grep -o "/Microsoft_.*pkg" | cut -d "_" -f 3)

but it does not match the latest version 16.47.1, as the download is not the latest version.

**Comment by Theile** [comment]
We have the same problem with OneDrive:
```
2021-04-12 09:00:08 microsoftonedrive found app at /Applications/OneDrive.app, version 21.052.0314 
2021-04-12 09:00:08 microsoftonedrive Latest version of OneDrive is 21.030.0211 
2021-04-12 09:00:08 microsoftonedrive Downloading https://go.microsoft.com/fwlink/?linkid=823060 to OneDrive.pkg 

```
I would have thought that the Microsoft Autoupdate component should have been started here, but this happens:
```
2021-04-12 09:03:39 microsoftonedrive Installing OneDrive.pkg to / installer: Package name is Microsoft OneDrive installer: Upgrading at base path / installer: The upgrade was successful. 
2021-04-12 09:04:16 microsoftonedrive found app at /Applications/OneDrive.app, version 21.052.0314 
2021-04-12 09:04:16 microsoftonedrive Installed OneDrive, version 21.052.0314 
2021-04-12 09:04:16 microsoftonedrive notifying 
2021-04-12 09:04:16 microsoftonedrive Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.fGbpqKLR 2021-04-12 09:04:16 microsoftonedrive Telling app OneDrive to open 
2021-04-12 09:04:16 microsoftonedrive Reopened OneDrive as lmn

```
And when opened, the user reports that it demanded to get new authentication. Maybe the `open` command is not working as expected. Also it gives som strange process output from the `open` command.

Also the version installed was already the newest one. So macadmins.software is not working for the version.
In this case we should get the version from the download link, like this:
```
downloadURL="https://go.microsoft.com/fwlink/?linkid=823060"
appNewVersion=$(curl -fsIL "$downloadURL" | grep -i location: | cut -d "/" -f 6 | cut -d "." -f 1-3)

```
I change the appnewVersion for the Microsoft labels that currently use macadmin.software.
But shouldn't autoupdate have kicked in?

**Comment by Theile** [comment]
So I have been going through the microsoft labels, and I'm not fully certain that we should include the `appNewVersion` at all.

My concern is if we omit appNewVersion, then the script will download the pkg before any version is matched, so when running automatically, it can give a lot of downloads.

I think we should force the script to do the autoupdate, when we have the app install already, then we don't need the version check in the script.
