### ISSUE TITLE
TeXShop Label Update to Point to Official Source vs GitHub

### ISSUE THREAD

**Issue by uurazzle** [Installomator/Installomator#1486]
Hi:

I reached out to the developer, Max Horn, and the GitHub repository is an unofficial mirror and is manually updated by the developer on occasion. The only official source is https://pages.uoregon.edu/koch/texshop/ and the label should use that source.

So, I have the following updated TeXShop label:

```
texshop)
    name="TeXShop"
    type="zip"
    downloadURL="https://pages.uoregon.edu/koch/texshop/texshop-64/texshop.zip"
    expectedTeamID="RBGCY5RJWM"
    ;;
```

**Comment by kryptonit1** [comment]
The reason to why the GitHub repo is being used is mentioned in #1188. I would also prefer if the official source was used, but just as the original label contributor I find the official download URL (https://pages.uoregon.edu/koch/texshop/texshop-64/texshop.zip) to be slow and quite unreliable.

**Comment by uurazzle** [comment]
Hi @kryptonit1,

Ok, but from the developer, Max Horn, the GitHub repository is an unofficial mirror and is manually updated by the developer on occasion. So, IMHO, slow and latest version is better than fast and out-dated version of software.

**Comment by kryptonit1** [comment]
> Hi @kryptonit1,
> 
> Ok, but from the developer, Max Horn, the GitHub repository is an unofficial mirror and is manually updated by the developer on occasion. So, IMHO, the slow and latest version is better than a fast and outdated version of the software.
> 
> I would recommend giving the developer feedback about the speed to see if you can motivate him to actively update the GitHub repository.

I've had downloads completely fail on several occasions when using the original source, so the reliability is a bigger problem. Especially if you want to use the label for update/patch workflows and not just initial installations.

I think it would probably be better to reach out to the main developer of TeXShop and maintainer of the original source (Richard Koch) and check if it would be possible for him to use a faster and more reliable distribution point for the software instead of https://pages.uoregon.edu/koch/texshop/texshop-64/texshop.zip. But I personally don't have the time for that at the moment.

**Comment by uurazzle** [comment]
Hi @kryptonit1 ,

I appreciate your feedback. However, in my humble opinion, if addressing GitHub comments is a priority or if you have the capacity to respond to them, you likely have the time to reach out to the maintainer of the original source as well. While I will personally contact them, I encourage others in the community affected by this issue to do the same. This ensures that it doesn't seem like I am the sole individual raising concerns or merely being labeled as a "complainer."

**Comment by kryptonit1** [comment]
> Hi @kryptonit1 ,
> 
> I appreciate your feedback. However, in my humble opinion, if addressing GitHub comments is a priority or if you have the capacity to respond to them, you likely have the time to reach out to the maintainer of the original source as well. While I will personally contact them, I encourage others in the community affected by this issue to do the same. This ensures that it doesn't seem like I am the sole individual raising concerns or merely being labeled as a "complainer."

You're the one raising the concern about the the label not pointing to the official source, and I provided a reason to why that's currently the case. I'm in no way responsible for the current TeXShop label and I've got no obligations to reach out to the developer in order to get this fixed. If this is an urgent matter in your case, then I suggest that you reach out to the developer and create a PR with the changes to the label that you would like to be implemented.

**Comment by uurazzle** [comment]
Hi @kryptonit1, 

Again, thanks for the feedback. But, it seems like we are talking in circles.

I have my custom label set up for TexShop, and it meets the needs of my environment. I have contacted the developer and need others using Installomator and the TexShope label to motivate him to use GitHub vs the web repository.  I will submit my custom label back to the Installomator project and the maintainers can decide to use the current outdated GitHub repository or the updated slow web repository going forward.

**Comment by Theile** [comment]
I think we should move the discussion to PR #1584. 

I understand that renaming a label might not be an optimum situation, but I think we should have the nem `texshop` for the developer release and the other distribution as an alternative.
