### ISSUE TITLE
Question: Custom TeamViewer QS with Kandji

### ISSUE THREAD

**Issue by kMikaZu** [Installomator/Installomator#1507]
For a client, I'm using Kandji as an MDM. I installed Installomator as a `.pkg` and I want to install TeamViewer QS Custom. But how I define the `teamviewerCustomDownloadURL` ? Do I need to fit it somewhere in `installomatorOptions`

Thanks for your help!

**Comment by acodega** [comment]
This slipped by somehow. Sorry about that. For the sake of documentation if anyone else comes across it, any variables you pass along with the label will be used instead of what's in the label. In your case the script that is calling the locally installed Installomator and providing the label to use, can also provide teamviewerCustomDownloadURL. ([See wiki](url))

An Installomator command would look like this: `/usr/local/Installomator/Installomator.sh teamviewerqscustom teamviewerCustomDownloadURL="url goes here"
