### ISSUE TITLE
Webex teams failing

### ISSUE THREAD

**Issue by Simply-Guy** [Installomator/Installomator#156]
Installing Webex Teams seems not to work. I think the .dmg file is no longer available without logging in.

**Comment by midni9ht** [comment]
Hey @Simply-Guy 
Webex Teams has been renamed to just 'Webex.app', which caused Installomator to fail, because the application name could not be fount within the downloaded DMG.
I just created a pull request (#164 ) to reflect that change and also add support for Apple Silicon at the same time.
This should solve the problem for you ;-)

**Comment by Theile** [comment]
Thanks, I think that has been fixed now.
