### ISSUE TITLE
Jamf Update Policy

### ISSUE THREAD

**Issue by oneguynick** [Installomator/Installomator#342]
I am currently using Jamf Pro with Installomator script to install several programs. It seems that some programs are updating a few times a day, but the version doesn't appear to increase. A few programs I have witnessed in the past few days:

- SF Fonts
- Mac FUSE
- Google Drive

I am running the v8.0 version of the script, and my Jamf Policy is set for:

- Frequency = Ongoing
- Trigger = Checkin
- All Computers // All Users

Any help is appreciated. I am not sure what the best blend of Jamf Policy settings are to push software initially, update when there is an update, and simply baseline all my systems.

**Comment by acodega** [comment]
A label needs an `appNewVersion` definition to support updating an app if it's out of date. [The Zoom label for example](https://github.com/Installomator/Installomator/blob/dev/fragments/labels/zoom.sh).

Google Drive doesn't have one, and I believe the others listed do not either. Installomator does have logic for checking if a downloaded pkg matches what's already installed but it only works with certain labels/apps.

I would recommend using logic on the Jamf side rather than having computers doing a lot of local activity running scripts more than necessary. This does get tricky I'll be honest, because using Jamf Patch policies runs the risk of using logic in Jamf to decide when to run Installomator but then Installomator performs it's version check, (when `appNewVersion` is defined), which is based on different logic. So basically Jamf says, "Run this policy, the app is out of date" and Installomator runs and says, "Nothing to install, according to my logic, the app is up to date". Installomator has its way of determining app versions which vary based on the app, and Jamf has its definitions and they don't always match. (Installomator primarily does version checks by cURLing a app's public download page for the latest version number or an RSS feed from the app distributor.)

**Comment by oneguynick** [comment]
Thank you for your response. That clears things up and I will spend some time trying to determine the best logic within Jamf.

**Comment by adibue** [comment]
Hi @oneguynick , we basically use the patch definitions from the Jamf Pro patch management framework to do this task.
There is a great example from @scriptingosx  on how to set up this workflow:
https://scriptingosx.com/2020/06/using-installomator-with-jamf-pro/

This works pretty good for us so far.
