### ISSUE TITLE
Signal has now an universal installer

### ISSUE THREAD

**Issue by Dragao75** [Installomator/Installomator#362]
With the current lookup for the download file:  `downloadURL=https://updates.signal.org/desktop/$(curl -fs https://updates.signal.org/desktop/latest-mac.yml | awk '/url/ && /dmg/ {print $3}') `
the wrong file is selected. The outcome for `$(curl -fs https://updates.signal.org/desktop/latest-mac.yml | awk '/url/ && /dmg/ {print $3}') ` : 
**signal-desktop-mac-x64-5.27.0.dmg
signal-desktop-mac-arm64-5.27.0.dmg
signal-desktop-mac-universal-5.27.0.dmg**

Adding | tail -1 add the end will give you the universal installer which of course will work for intel and arm64 
`downloadURL=https://updates.signal.org/desktop/$(curl -fs https://updates.signal.org/desktop/latest-mac.yml | awk '/url/ && /dmg/ {print $3}' | tail -1)`

**Comment by Dragao75** [comment]
other solutions are possible.. (grep on universal perhaps)

**Comment by fleish** [comment]
Chiming in to specifically point out this breaks Installomator's attempts to download Signal:

`+./Installomator.sh:3097> downloadURL=$'https://updates.signal.org/desktop/signal-desktop-mac-x64-5.27.0.dmg\nsignal-desktop-mac-arm64-5.27.0.dmg\nsignal-desktop-mac-universal-5.27.0.dmg' 
`

**Comment by Theile** [comment]
If a universal version exist, then we will go with that, instead of specifying different versions.

Fixed it here: [https://github.com/Installomator/Installomator/pull/359/files#diff-a43e3353414dfe78e88653ab9c854c2d885926c27e90144f6bee3026bb491133](https://github.com/Installomator/Installomator/pull/359/files#diff-a43e3353414dfe78e88653ab9c854c2d885926c27e90144f6bee3026bb491133)
