### ISSUE TITLE
Microsoft Visual Studio Code and the blockingProcess

### ISSUE THREAD

**Issue by adibue** [Installomator/Installomator#379]
Hello, fellow MacSysAdmins.

I have the problem with **Visual Studio Code** that no blocking process is found when `blockingProcesses` is set to `( Code )`. However, it works fine when set to `( Electron )`, which is of course very unsexy as other running applications might also use Electron as their process.

Do you have the same problem? Is there perhaps a better way to correctly identify a running VS code in Installomator?

**Comment by acodega** [comment]
I thought we had an open Issue for this, we've run in to this before, particularly with Visual Studio Code. The way we check running processes right now is too strict, however I haven't had time/knowledge to think through how we can improve it without then causing false positives. Removing -x, `pgrep -i Code`, which requires an exact match of the process name, returns a result when Visual Studio Code is running.

**Comment by acodega** [comment]
I'm going to mark this as enhancement, it's not a bug since prep is working they way we've written it, but an improvement in process matching is needed. So far I haven't found other apps, including Slack or Teams, which are found when using `prep -ix Electron`. Maybe we should change the label to those processes, with a comment warning to test locally to avoid false positives.

**Comment by acodega** [comment]
@mrazishere want to open a PR to change the blockingProcess to `Code Helper` ?

**Comment by michael-zukrow-da** [comment]
could pgrep -fi "visual studio code.app/content" be used? seems more future proof

**Comment by asri-tm** [comment]
i have since stopped using installomator for vs code deployment/patching, even with the `blockingProcesses` updated to Electron, I can never get the script to kill the process with the `prompt_user_then_kill` action without getting endless prompts.

modified [this](https://github.com/alectrona/install-update-app-in-dmg/blob/master/install-update-app-in-dmg.sh) to support zip archives and works perfectly for vs code deployment/patching

Single prompt, kills process, proceed to update and relaunch app.
