### ISSUE TITLE
Feature request: uninstaller for applications titles

### ISSUE THREAD

**Issue by kylejericson** [Installomator/Installomator#442]
Is there a way we could get uninstallers added for titles in this script?
I see this as removing files from these locations:
/Applications
/Library/Application Support
/Library/Containers
~/Library/Application Support
~/Library/Containers

I think the main things needed to do this is are already in the script app name and bundle id.

**Comment by Theile** [comment]
There is nothing in Installomator that can help remove installed files. 

To uninstall you need the bom-file from pkgs that shows what was installed, and then those should be deleted. If it was an app that was copied, then that can be removed but what about the data that the app installed in the folders you mention?

It would be specialized for each software title, and impossible for anyone to maintain. 

So that will never be part of Installomator. 

On certain software titles an uninstaller is provided and that will always be the best.
