### ISSUE TITLE
Removal of dmg installer for firefox & chrome

### ISSUE THREAD

**Issue by fleish** [Installomator/Installomator#451]
I noticed this in the 9.1 release notes:

> Note: Both Google and Mozilla recommend using the pkg installers instead of the dmg downloads for managed deployments. So far, Installomator has provided labels for both. (googlechrome and googlechromepkg or firefox and firefoxpkg, respectively) Since there are problems with the dmg downloads, a future release of Installomator will disable the firefox and googlechrome dmg labels. You should switch to using the respective pkg labels instead.

Rather than remove dmg download labels, could Installomator be updated to also use them for the pkg downloads as well? That would ensure anyone still using them would get continuity should this not know to update their labels.

**Comment by scriptingosx** [comment]
We can do this and have done so in the past for other software changes.

Here is _my_ reasoning why I would not want to do this: The software installed by the pkg installers is _different_ than the dmg downloads. Both pkg installers also install the extra software for updates. I (and the developers) consider this an advantage for managed deployments, since it removes the necessity prompting the user for this extra functionality.

But since this is change in the software's behavior, I am reluctant to make this change transparent. And administrator might have reasons to not want the update functionality installed and might not notice the change. I breaking the existing labels, will force admins to make a conscious decision, rather than us making it for them.

That said, I am open for discussion on this. (Here, or join the #installomator channel on MacAdmins Slack.)
