### ISSUE TITLE
Rancher Desktop

### ISSUE THREAD

**Issue by jciv87** [Installomator/Installomator#488]
When using the supplied labels for this desktop app I receive this:

![Screen Shot 2022-04-13 at 3 53 41 PM](https://user-images.githubusercontent.com/50222175/163259477-f08f58fe-2797-4ff2-8931-679da66830f9.png)

I used the buildlabel.sh to get this to function properly:

rancherdesktop)
    name="Rancher Desktop"
    type="zip"
if [[ $(arch) != "i386" ]]; then
        printlog "Architecture: arm64 (not i386)"
        downloadURL="https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.2.1/Rancher.Desktop-1.2.1-mac.aarch64.zip"
         appNewVersion="$(versionFromGit rancher-sandbox rancher-desktop)"
    else
        printlog "Architecture: i386"
        downloadURL="https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.2.1/Rancher.Desktop-1.2.1-mac.x86_64.zip"
        appNewVersion="$(versionFromGit rancher-sandbox rancher-desktop)"
    fi
    expectedTeamID="2Q6FHJR3H3"
    appName="Rancher Desktop.app"
    ;;

**Comment by acodega** [comment]
There's a couple things going on here.

We'd prefer not to use `printlog` inside of app labels. It can cause unique errors and unique verbiage from app to app, this makes it harder to troubleshoot logs when there isn't consistent messaging. 

Your appNewVersion doesn't need to be in the if statement since it's the same value regardless of the architecture.  

Lastly, you can still provide the downloadURL in the form of `downloadURLFromGit`. Since there are different archives for the two platforms, you can specify `archiveName`, making sure to place it before downloadURL in the label, and do your if logic there. See [Pritunl](https://github.com/Installomator/Installomator/blob/401d5ad1389fab9e78b0b0ae6ad09fdca1120e58/Installomator.sh#L2173) and [Ferdi](https://github.com/Installomator/Installomator/blob/401d5ad1389fab9e78b0b0ae6ad09fdca1120e58/Installomator.sh#L3720) as examples.

**Comment by scriptingosx** [comment]
I believe this was fixed with #463  in Installomator v9.2

Closing
