### ISSUE TITLE
a bug, or not a bug?

### ISSUE THREAD

**Issue by macmangr** [Installomator/Installomator#594]
I'm testing the following label I created and I'm noticing a strange behavior. The software is first downloaded and only during installation is it compared with the existing version so that the message appears that no installation is necessary.

"
jdk18)
    name="Java SE Development Kit 18"
    type="pkgInDmg"
    appNewVersion=$(curl -sf "https://www.oracle.com/java/technologies/downloads/#jdk18-mac" | grep -m 1 "Java SE Development Kit" | sed "s|.*Kit \(.*\) downloads.*|\\1|")
    packageID="com.oracle.jdk-${appNewVersion}"
    versionKey="CFBundleShortVersionString"
    if [[ $(arch) == "arm64" ]]; then
        downloadURL="https://download.oracle.com/java/18/latest/jdk-18_macos-aarch64_bin.dmg"
    elif [[ $(arch) == "i386" ]]; then
        downloadURL="https://download.oracle.com/java/18/latest/jdk-18_macos-x64_bin.dmg"
    fi
    expectedTeamID="VB5E2TV963"
    ;;
"

If I use the same label information in a "Manual valuesfromarguments" script, it works fine. It is first compared with the existing version and no download is started.

"
downloadURL=https://download.oracle.com/java/18/latest/jdk-18_macos-x64_bin.dmg
appNewVersion=$(curl -sf "https://www.oracle.com/java/technologies/downloads/#jdk18-mac" | grep -m 1 "Java SE Development Kit" | sed "s|.*Kit \(.*\) downloads.*|\\1|")

cmdOutput="$(${destFile} valuesfromarguments LOGO=$LOGO \
    name=\"Java\ SE\ Development\ Kit\" \
    type=pkgInDmg \
    downloadURL=$downloadURL \
    appNewVersion=$appNewVersion \
    packageID="com.oracle.jdk-${appNewVersion}"
    expectedTeamID=VB5E2TV963 \
    BLOCKING_PROCESS_ACTION=prompt_user \
    LOGGING=REQ \
    NOTIFY=all || true)"
"

Is this a bug in the installomator or am I doing something wrong?

**Comment by acodega** [comment]
So your post isn't formatting the text properly as code.. however I think I already see the difference. Your `valuesfromarguments` is not passing the custom `versionKey`. That is specified in your jdk18 label. 

To test you can run `defaults read [path to app]/Contents/Info.plist CFBundleShortVersionString` or `CFBundleVersion` and see if the result is provided.

Also keep in mind `packageID` is used to check the package receipt of the installed app, so you can't use `appNewVersion` in the `packageID` value because it won't exist.

**Comment by acodega** [comment]
Sorry.. I'm realizing things after I posted my original post. packageID won't really work since you don't know the package receipt to look for since each version has a unique receipt name.

If you look at the Zulu JDK labels, you can accomplish version checking by running the java command, or (since JDK does this) read the currently installed versions Info.plist located at `/Library/Java/JavaVirtualMachines...` You can specify a appCustomVersion value, take a look at the `zulujdk8` label.

**Comment by macmangr** [comment]
Thanks, I'll look at the Zulu labels to find the solution.

**Comment by macmangr** [comment]
Thanks to @acodega  for the tip and to @kdrwygvh for the zulu labels. I got the version check for Java JDK working.
