### ISSUE TITLE
New Label: ClickUp

### ISSUE THREAD

**Issue by BClare19** [Installomator/Installomator#631]
Hey,

Could we please have ClickUp Desktop app installation added to the labels?  Thanks

https://clickup.com/download

**Comment by acodega** [comment]
Looks like the Apple Silicon app is a drag and drop .app so that's not an issue but the Intel app is a click to run installer. Also do you know if there's any release notes available for the Mc app itself,  not the product as a whole? We could scrap it for new version info, although I bet the app itself doesn't need to be updated much anyway.

**Comment by dnikles** [comment]
PR that may close this https://github.com/Installomator/Installomator/pull/896
