### ISSUE TITLE
Make notification message template one or more variables

### ISSUE THREAD

**Issue by apizz** [Installomator/Installomator#70]
Rather than needing to alter the script itself when used (https://github.com/scriptingosx/Installomator/blob/dev/Installomator.sh#L1530-L1541), would like to see one or more custom variables be added to allow easier customization of the notification message presented, if enabled, for users.

Along these same lines, would like to be able to customize the application image.  As it is now, within the context of a Jamf deployment, most users don't know Jamf or the Jamf Management logo, so it would be helpful to be able to either automatically use the the one used to customize Self Service, or simply provide a path to the desired image to be included in the message.

**Comment by scriptingosx** [comment]
It is _not_ technically possible to change the icon with the notification solutions used in installomator (Management Action or osascript).

There are some notifier solutions that allow for re-branding the icon, but usually by re-building the app with your own. for example https://github.com/dataJAR/Notifier

If you want to add another option to the `displaynotification` function, please file a pull request.

I am keeping this issue open because I like the original suggestion to allow for better customization of the notification message.

**Comment by apizz** [comment]
@scriptingosx I've tested and confirmed indeed that if sent to Management Action that you can't, but with `osascript` it appears you can.  I'm still working on a PR, but this I've taken from part of the work I've done:

```
runAsUser osascript -e "button returned of (display dialog \"$message\" with title \"$title\" buttons {\"$nodialogbutton\", \"$updatedialogbutton\"} default button \"$updatedialogbutton\" with icon POSIX file \"$CUSTOM_DIALOG_ICON\")"
```

**Comment by Theile** [comment]
This script example is for `display Dialog` and not for notifications.
